### ISSUE TITLE
Any idea or solution to decrease the computation cost

### ISSUE THREAD

**Issue by jchhuang** [tngh5004/Omnistitch#10]
The computation cost of current algo version is too high for edge device，so do you have any idea or solution to increase the computation overhead

**Comment by tngh5004** [comment]
I think there are ways to avoid using cost volume, or to use average splatting instead of softmax splatting. The effectiveness of this is described in the paper.

**Comment by jchhuang** [comment]
Does the "cost volume" mentioned here denote the “3D depth cost”? However, in the ablation study, you said the “3D depth cost” is very important for the stitching performance.

**Comment by jchhuang** [comment]
In your final version publication in ACM MM 2024，you mentioned further analysis about computational cost have been added to the supplementary materials，so may you share the final version‘s supplementary materials? thanks
