### ISSUE TITLE
Lots of case of generating GV360 are failed, any solutions to improve the success rate

### ISSUE THREAD

**Issue by jchhuang** [tngh5004/Omnistitch#11]
Hi, when use you provided configuration case to generate GV360，lots of the cases are failed, do you have any solutions to optimize this issue?
![failed case](https://github.com/user-attachments/assets/d974108c-f222-4569-8c36-5d26e7cc64a8)

**Comment by tngh5004** [comment]
Without knowing your exact configuration, it's hard to give advice.
