### ISSUE TITLE
environment configuration

### ISSUE THREAD

**Issue by jchhuang** [tngh5004/Omnistitch#4]
When running the data generation code, lots of the errors about carla are encountered, so may you share which version of Carla and python are used in your project？

**Comment by tngh5004** [comment]
> When running the data generation code, lots of the errors about carla are encountered, so may you share which version of Carla and python are used in your project？

I apologize for the slow reply, I've had some personal stuff going on. I used carla version 0.9.11 for data collection.

**Comment by jchhuang** [comment]
> > When running the data generation code, lots of the errors about carla are encountered, so may you share which version of Carla and python are used in your project？
> 
> I apologize for the slow reply, I've had some personal stuff going on. I used carla version 0.9.11 for data collection.

Thanks lot for your reply.
