### ISSUE TITLE
How to add fisheye camera function to the Carla

### ISSUE THREAD

**Issue by jchhuang** [tngh5004/Omnistitch#5]
When I running the dataset generation code, it reports "blueprint 'sensor.camera.fisheye' not found". After studying, I know that the original carla do not has the function of “fisheye camera”，so may you share how to add the function of fisheye camera to carla？

**Comment by tngh5004** [comment]
> When I running the dataset generation code, it reports "blueprint 'sensor.camera.fisheye' not found". After studying, I know that the original carla do not has the function of “fisheye camera”，so may you share how to add the function of fisheye camera to carla？

You will need to add a fisheye lens, which can be found in the repository below.  
https://github.com/carla-simulator/carla/pull/3755
