### ISSUE TITLE
Which file is the groundtrue in the dataset generated by the Generation_trainset?

### ISSUE THREAD

**Issue by jchhuang** [tngh5004/Omnistitch#6]
Which file is the groundtrue in the dataset generated by the Generation_trainset?

**Comment by tngh5004** [comment]
> Which file is the groundtrue in the dataset generated by the Generation_trainset?

You're right, but in my opinion, the validation set(test_set) code is cleaned up once, so it might be more helpful to refer to it.

**Comment by jchhuang** [comment]
Sorry, I don't get what your meaning. As for the Generation_trainset will generate lots of images with different yaw angles (e.g. in the case of RU, there are 0', 3', 6', ……, 90')，but which image will be selected as the ground truth of the stitched results？

**Comment by tngh5004** [comment]
https://github.com/tngh5004/Omnistitch/issues/9#issuecomment-2367001765

I think I answered your other question in the link above.
