### ISSUE TITLE
camera position calculation

### ISSUE THREAD

**Issue by jchhuang** [tngh5004/Omnistitch#7]
In the /scripts/GV360_generation_scripts, this repo calculates all the camera position which is distributed as 3-degree yaw intervals, however I found the position of the camera is wrong, for example when yaw = 3, I got the (y = 0.0588, x = 1.1219) while your are (y = 0.0647, x = 1.2337). So pls check your calculation.

**Comment by tngh5004** [comment]
> In the /scripts/GV360_generation_scripts, this repo calculates all the camera position which is distributed as 3-degree yaw intervals, however I found the position of the camera is wrong, for example when yaw = 3, I got the (y = 0.0588, x = 1.1219) while your are (y = 0.0647, x = 1.2337). So pls check your calculation.

The configuration of my dataset is to place the cameras at the appropriate angles along the circumference of the circle, and your setup will probably be different.
And this will continue to change as the distance between the cameras increases, so you'll want to make sure.
But I could be wrong, so I'll check and get back to you if I'm wrong.
