### ISSUE TITLE
About Tensorboard

### ISSUE THREAD

**Issue by DMH517** [tngh5004/Omnistitch#8]
Hi author, I would like to ask something about what is shown in Tensorboard. As shown, are 0/0, 1/0, 2/0, as well as 3/0 images in a batch (by random rotation, channel inversion, etc.)? Also 0/1, 1/1, 2/1, and 3/1 predict which stage of who's optical flow?
![Tensorboard](https://github.com/user-attachments/assets/27d7faa9-240f-422f-95b2-c1e7441683b5)

**Comment by DMH517** [comment]
There is also the problem that in the three images shown in the left half of the above image (respectively, the overlapping image, the label, and the predicted result). The difference between the pairs of to-be-stitched images is very small, with only very little ghost, which is very inconsistent with my preprocessing results. May I ask how you achieved this result by preprocessing the fisheye images? I can't achieve this level of fisheye image correction and therefore the panoramic stitching is not as good as it could be. **Looking forward to your reply!**

**Comment by tngh5004** [comment]
> Hi author, I would like to ask something about what is shown in Tensorboard. As shown, are 0/0, 1/0, 2/0, as well as 3/0 images in a batch (by random rotation, channel inversion, etc.)? Also 0/1, 1/1, 2/1, and 3/1 predict which stage of who's optical flow? ![Tensorboard](https://private-user-images.githubusercontent.com/179601590/365142433-27d7faa9-240f-422f-95b2-c1e7441683b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDQ2MDIsIm5iZiI6MTcyNTg0NDMwMiwicGF0aCI6Ii8xNzk2MDE1OTAvMzY1MTQyNDMzLTI3ZDdmYWE5LTI0MGYtNDIyZi05NWIyLWMxZTc0NDE2ODNiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTcyM2ExYjY0OTJlYzY4N2IyYTZiZTk5NTg3ZjBlN2Q0NWIyM2NlZTJhOGIxMzBjYzlhODQzMmY5YjJiOTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zH_5fJEOC1BdqEUFRC8TONOfeMfMOTrh1URyN6ja0MA)

1. As you said, the image pairs of 0/0, 1/0, 2/0, 3/0 have data augmentation of random rotation, channel inversion, etc. It's just a coincidence that they look different in each batch.
(It's just randomized).
2. The optical flow seen in 0/1 through 3/1 is a prediction of the flow between the two input images of the image pair at x/0.
Note that the image pair is of the form (img0/groundtruth/img1).
And the optical flow map shows the direction of the moving pixels for each color, and the intensity of the flow for each color. You'll need to do a search for this.

**Comment by tngh5004** [comment]
> There is also the problem that in the three images shown in the left half of the above image (respectively, the overlapping image, the label, and the predicted result). The difference between the pairs of to-be-stitched images is very small, with only very little ghost, which is very inconsistent with my preprocessing results. May I ask how you achieved this result by preprocessing the fisheye images? I can't achieve this level of fisheye image correction and therefore the panoramic stitching is not as good as it could be. **Looking forward to your reply!**

Please understand that we cannot disclose the unwarping technology because it is our proprietary technology, and when used in the real environment, ghosting is a disadvantage of optical flow base stitching, and it is something that needs to be improved in further research.

**Comment by DMH517** [comment]
> > Hi author, I would like to ask something about what is shown in Tensorboard. As shown, are 0/0, 1/0, 2/0, as well as 3/0 images in a batch (by random rotation, channel inversion, etc.)? Also 0/1, 1/1, 2/1, and 3/1 predict which stage of who's optical flow? ![Tensorboard](https://private-user-images.githubusercontent.com/179601590/365142433-27d7faa9-240f-422f-95b2-c1e7441683b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDQ2MDIsIm5iZiI6MTcyNTg0NDMwMiwicGF0aCI6Ii8xNzk2MDE1OTAvMzY1MTQyNDMzLTI3ZDdmYWE5LTI0MGYtNDIyZi05NWIyLWMxZTc0NDE2ODNiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTcyM2ExYjY0OTJlYzY4N2IyYTZiZTk5NTg3ZjBlN2Q0NWIyM2NlZTJhOGIxMzBjYzlhODQzMmY5YjJiOTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zH_5fJEOC1BdqEUFRC8TONOfeMfMOTrh1URyN6ja0MA)
> 
> 1. As you said, the image pairs of 0/0, 1/0, 2/0, 3/0 have data augmentation of random rotation, channel inversion, etc. It's just a coincidence that they look different in each batch.
>    (It's just randomized).
> 2. The optical flow seen in 0/1 through 3/1 is a prediction of the flow between the two input images of the image pair at x/0.
>    Note that the image pair is of the form (img0/groundtruth/img1).
>    And the optical flow map shows the direction of the moving pixels for each color, and the intensity of the flow for each color. You'll need to do a search for this.
Thanks for the answer, I don't really know much about optical flow technology and as you said I really should brush up on my knowledge. Another confusion I have is that is the optical flow in the Step1 the same thing as the optical flow in the figure above (it feels like a big difference)?

**Comment by DMH517** [comment]
> > Hi author, I would like to ask something about what is shown in Tensorboard. As shown, are 0/0, 1/0, 2/0, as well as 3/0 images in a batch (by random rotation, channel inversion, etc.)? Also 0/1, 1/1, 2/1, and 3/1 predict which stage of who's optical flow? ![Tensorboard](https://private-user-images.githubusercontent.com/179601590/365142433-27d7faa9-240f-422f-95b2-c1e7441683b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDQ2MDIsIm5iZiI6MTcyNTg0NDMwMiwicGF0aCI6Ii8xNzk2MDE1OTAvMzY1MTQyNDMzLTI3ZDdmYWE5LTI0MGYtNDIyZi05NWIyLWMxZTc0NDE2ODNiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTcyM2ExYjY0OTJlYzY4N2IyYTZiZTk5NTg3ZjBlN2Q0NWIyM2NlZTJhOGIxMzBjYzlhODQzMmY5YjJiOTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zH_5fJEOC1BdqEUFRC8TONOfeMfMOTrh1URyN6ja0MA)
> 
> 1. As you said, the image pairs of 0/0, 1/0, 2/0, 3/0 have data augmentation of random rotation, channel inversion, etc. It's just a coincidence that they look different in each batch.
>    (It's just randomized).
> 2. The optical flow seen in 0/1 through 3/1 is a prediction of the flow between the two input images of the image pair at x/0.
>    Note that the image pair is of the form (img0/groundtruth/img1).
>    And the optical flow map shows the direction of the moving pixels for each color, and the intensity of the flow for each color. You'll need to do a search for this.

Thanks for the answer, I don't really know much about optical flow technology and as you said I really should brush up on my knowledge. Another confusion I have is that is the optical flow in the Step1 the same thing as the optical flow in the figure above (it feels like a big difference)? 
![image](https://github.com/user-attachments/assets/7a03d71d-7e2f-4f50-abd1-27a33c68f26d)

**Comment by tngh5004** [comment]
> > > Hi author, I would like to ask something about what is shown in Tensorboard. As shown, are 0/0, 1/0, 2/0, as well as 3/0 images in a batch (by random rotation, channel inversion, etc.)? Also 0/1, 1/1, 2/1, and 3/1 predict which stage of who's optical flow? ![Tensorboard](https://private-user-images.githubusercontent.com/179601590/365142433-27d7faa9-240f-422f-95b2-c1e7441683b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDQ2MDIsIm5iZiI6MTcyNTg0NDMwMiwicGF0aCI6Ii8xNzk2MDE1OTAvMzY1MTQyNDMzLTI3ZDdmYWE5LTI0MGYtNDIyZi05NWIyLWMxZTc0NDE2ODNiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTcyM2ExYjY0OTJlYzY4N2IyYTZiZTk5NTg3ZjBlN2Q0NWIyM2NlZTJhOGIxMzBjYzlhODQzMmY5YjJiOTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zH_5fJEOC1BdqEUFRC8TONOfeMfMOTrh1URyN6ja0MA)
> > 
> > 
> > 
> > 1. As you said, the image pairs of 0/0, 1/0, 2/0, 3/0 have data augmentation of random rotation, channel inversion, etc. It's just a coincidence that they look different in each batch.
> >    (It's just randomized).
> > 2. The optical flow seen in 0/1 through 3/1 is a prediction of the flow between the two input images of the image pair at x/0.
> >    Note that the image pair is of the form (img0/groundtruth/img1).
> >    And the optical flow map shows the direction of the moving pixels for each color, and the intensity of the flow for each color. You'll need to do a search for this.
> 
> Thanks for the answer, I don't really know much about optical flow technology and as you said I really should brush up on my knowledge. Another confusion I have is that is the optical flow in the Step1 the same thing as the optical flow in the figure above (it feels like a big difference)? ![image](https://private-user-images.githubusercontent.com/179601590/365617713-7a03d71d-7e2f-4f50-abd1-27a33c68f26d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNDU2NDYsIm5iZiI6MTcyNzA0NTM0NiwicGF0aCI6Ii8xNzk2MDE1OTAvMzY1NjE3NzEzLTdhMDNkNzFkLTdlMmYtNGY1MC1hYmQxLTI3YTMzYzY4ZjI2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQyMjQ5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTcxN2JiOTQ3YjhhNGE0NzljNDBmODlhYTU3NjIxZjM2YjAwNzg1ZDkxNzM1MjgzOWFiNThiYjc2ODkwMDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I8ctcesBblYA6s0p-ZmyHmuCXq5a5VFIdOpJdTlcl3w)

I must have misunderstood, you are right, the optical flow on the tensorboard is the same as the optical flow on the figure in the paper.

**Comment by DMH517** [comment]
> > > > 嗨，作者，我想问一些关于 Tensorboard 中显示的内容的问题。如图所示，批量中有 0/0、1/0、2/0 和 3/0 图像（通过随机旋转、通道反转等）？此外，0/1、1/1、2/1 和 3/1 预测了 Who's Optical Flow 的哪个阶段？![Tensorboard](https://private-user-images.githubusercontent.com/179601590/365142433-27d7faa9-240f-422f-95b2-c1e7441683b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDQ2MDIsIm5iZiI6MTcyNTg0NDMwMiwicGF0aCI6Ii8xNzk2MDE1OTAvMzY1MTQyNDMzLTI3ZDdmYWE5LTI0MGYtNDIyZi05NWIyLWMxZTc0NDE2ODNiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTcyM2ExYjY0OTJlYzY4N2IyYTZiZTk5NTg3ZjBlN2Q0NWIyM2NlZTJhOGIxMzBjYzlhODQzMmY5YjJiOTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zH_5fJEOC1BdqEUFRC8TONOfeMfMOTrh1URyN6ja0MA)
> > > 
> > > 
> > > 
> > > 1. 正如你所说，0/0、1/0、2/0、3/0 的图像对具有随机旋转、通道反转等数据增强。只是巧合的是，它们在每批中看起来都不同。 （它只是随机的）。
> > > 2. 在 0/1 到 3/1 中看到的光流是对图像对的两个输入图像在 x/0 处的流动的预测。请注意，图像对的格式为 （img0/groundtruth/img1）。光流图显示每种颜色的移动像素的方向，以及每种颜色的流强度。您需要对此进行搜索。
> > 
> > 
> > 感谢您的回答，我对光流技术了解不多，正如您所说，我真的应该复习一下我的知识。我的另一个困惑是，Step1 中的光流与上图中的光流是一回事吗（感觉差异很大）？![image](https://private-user-images.githubusercontent.com/179601590/365617713-7a03d71d-7e2f-4f50-abd1-27a33c68f26d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNDU2NDYsIm5iZiI6MTcyNzA0NTM0NiwicGF0aCI6Ii8xNzk2MDE1OTAvMzY1NjE3NzEzLTdhMDNkNzFkLTdlMmYtNGY1MC1hYmQxLTI3YTMzYzY4ZjI2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQyMjQ5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTcxN2JiOTQ3YjhhNGE0NzljNDBmODlhYTU3NjIxZjM2YjAwNzg1ZDkxNzM1MjgzOWFiNThiYjc2ODkwMDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I8ctcesBblYA6s0p-ZmyHmuCXq5a5VFIdOpJdTlcl3w)
> 
> 我一定是误会了，你是对的，tensorboard 上的光流和论文中图上的光流是一样的。

After reading your code in detail, as I understand it, the number of channel of bi_flow is 4. The first two channels are the optical flow from img0 to gt, and the last two channels are the optical flow from img1 to gt (that's what bi-directional flow estimation means). So what is shown in the Tensorboard is actually the content of the first two channels, which is the optical flow from **img0 to gt**. Is my understanding correct please? Thanks for your guidance!
![image](https://github.com/user-attachments/assets/6f691792-d148-47e7-98cc-e70c33f01f49)

**Comment by tngh5004** [comment]
> > > > > 嗨，作者，我想问一些关于 Tensorboard 中显示的内容的问题。如图所示，批量中有 0/0、1/0、2/0 和 3/0 图像（通过随机旋转、通道反转等）？此外，0/1、1/1、2/1 和 3/1 预测了 Who's Optical Flow 的哪个阶段？![Tensorboard](https://private-user-images.githubusercontent.com/179601590/365142433-27d7faa9-240f-422f-95b2-c1e7441683b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDQ2MDIsIm5iZiI6MTcyNTg0NDMwMiwicGF0aCI6Ii8xNzk2MDE1OTAvMzY1MTQyNDMzLTI3ZDdmYWE5LTI0MGYtNDIyZi05NWIyLWMxZTc0NDE2ODNiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTcyM2ExYjY0OTJlYzY4N2IyYTZiZTk5NTg3ZjBlN2Q0NWIyM2NlZTJhOGIxMzBjYzlhODQzMmY5YjJiOTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zH_5fJEOC1BdqEUFRC8TONOfeMfMOTrh1URyN6ja0MA)
> > > > 
> > > > 
> > > > 
> > > > 1. 正如你所说，0/0、1/0、2/0、3/0 的图像对具有随机旋转、通道反转等数据增强。只是巧合的是，它们在每批中看起来都不同。 （它只是随机的）。
> > > > 2. 在 0/1 到 3/1 中看到的光流是对图像对的两个输入图像在 x/0 处的流动的预测。请注意，图像对的格式为 （img0/groundtruth/img1）。光流图显示每种颜色的移动像素的方向，以及每种颜色的流强度。您需要对此进行搜索。
> > > 
> > > 
> > > 感谢您的回答，我对光流技术了解不多，正如您所说，我真的应该复习一下我的知识。我的另一个困惑是，Step1 中的光流与上图中的光流是一回事吗（感觉差异很大）？![image](https://private-user-images.githubusercontent.com/179601590/365617713-7a03d71d-7e2f-4f50-abd1-27a33c68f26d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNDU2NDYsIm5iZiI6MTcyNzA0NTM0NiwicGF0aCI6Ii8xNzk2MDE1OTAvMzY1NjE3NzEzLTdhMDNkNzFkLTdlMmYtNGY1MC1hYmQxLTI3YTMzYzY4ZjI2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQyMjQ5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTcxN2JiOTQ3YjhhNGE0NzljNDBmODlhYTU3NjIxZjM2YjAwNzg1ZDkxNzM1MjgzOWFiNThiYjc2ODkwMDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I8ctcesBblYA6s0p-ZmyHmuCXq5a5VFIdOpJdTlcl3w)
> > 
> > 
> > 我一定是误会了，你是对的，tensorboard 上的光流和论文中图上的光流是一样的。
> 
> After reading your code in detail, as I understand it, the number of channel of bi_flow is 4. The first two channels are the optical flow from img0 to gt, and the last two channels are the optical flow from img1 to gt (that's what bi-directional flow estimation means). So what is shown in the Tensorboard is actually the content of the first two channels, which is the optical flow from **img0 to gt**. Is my understanding correct please? Thanks for your guidance! ![image](https://private-user-images.githubusercontent.com/179601590/370243330-6f691792-d148-47e7-98cc-e70c33f01f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMjgzMjIsIm5iZiI6MTcyNzIyODAyMiwicGF0aCI6Ii8xNzk2MDE1OTAvMzcwMjQzMzMwLTZmNjkxNzkyLWQxNDgtNDdlNy05OGNjLWU3MGMzM2YwMWY0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMTMzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGViZDg5MjA5NjFkNTMzNmFiODAwYzg1YjRhOWU4NmNkYTEzODkzY2EyODY2ZDBmNDJiMmE1ZTUwNWYwMmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8oUF_3cVL61h-5QD4xg6uHUUxk5jh0kZjx9m_z4NeDs)

Yes you are right :)
Additionally, I think you are planning further experiments on this.
If so, consider limiting the flow.
When cut in half, the image at the center of the lens doesn't really need to move, so I would recommend scaling the flow away from the center of the lens (multiplying by 0-1). (And in this case, I would recommend not using softmax splatting).

I hope my answer is helpful.
