### ISSUE TITLE
May you provide the code of generating the ground truth images？

### ISSUE THREAD

**Issue by jchhuang** [tngh5004/Omnistitch#9]
As mentioned in the paper”The four ground-truth images are aligned for different input pairings: front-right (RU), right-back (RD), back-left (LD), and left-front (LU).   These GT images are derived by collecting the center pixels from camera inputs and continuously placing them along an ellipse.   This approach minimizes distortion and closely replicates a real-world panoramic view for each side.   We place 29 cameras on each of the four intermediate sides to ensure comprehensive coverage.  We then un-warp the camera inputs, crop the pixels closest to the center, and align and blend the cropped pixels to reduce camera distortion, creating what we consider to be the ground truth“，may you provide the corresponding code to generate the ground truth images？

**Comment by jchhuang** [comment]
@tngh5004 Do you note my message？

**Comment by tngh5004** [comment]
We recommend using a program called PTGUI for this process.

**Comment by tngh5004** [comment]
> As mentioned in the paper”The four ground-truth images are aligned for different input pairings: front-right (RU), right-back (RD), back-left (LD), and left-front (LU). These GT images are derived by collecting the center pixels from camera inputs and continuously placing them along an ellipse. This approach minimizes distortion and closely replicates a real-world panoramic view for each side. We place 29 cameras on each of the four intermediate sides to ensure comprehensive coverage. We then un-warp the camera inputs, crop the pixels closest to the center, and align and blend the cropped pixels to reduce camera distortion, creating what we consider to be the ground truth“，may you provide the corresponding code to generate the ground truth images？

I generated it using the original code of PTGUI (C++ based), so the output may be different from the most recent PTGUI version, but I don't think it's a big deal.

**Comment by jchhuang** [comment]
I also try to use the PTGUI to generate the ground truth, however the obtained image is a little blurry, do you encounter this issue and how to solve it?
